# Generated by Django 4.2.9 on 2026-03-14 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueueSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_queue_size",
                    models.PositiveIntegerField(
                        default=100, verbose_name="max queue size"
                    ),
                ),
                (
                    "average_consultation_time",
                    models.PositiveIntegerField(
                        default=15, verbose_name="average consultation time"
                    ),
                ),
                (
                    "token_prefixes",
                    models.JSONField(default=list, verbose_name="token prefixes"),
                ),
                (
                    "auto_advance",
                    models.BooleanField(default=True, verbose_name="auto advance"),
                ),
                (
                    "notification_enabled",
                    models.BooleanField(
                        default=True, verbose_name="notification enabled"
                    ),
                ),
                (
                    "clinic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_settings",
                        to="clinics.clinic",
                        verbose_name="clinic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Queue Settings",
                "verbose_name_plural": "Queue Settings",
                "db_table": "queue_settings",
            },
        ),
        migrations.CreateModel(
            name="QueueToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_number",
                    models.PositiveIntegerField(verbose_name="token number"),
                ),
                (
                    "token_label",
                    models.CharField(max_length=1, verbose_name="token label"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "Waiting"),
                            ("CALLED", "Called"),
                            ("WITH_DOCTOR", "With Doctor"),
                            ("COMPLETED", "Completed"),
                            ("SKIPPED", "Skipped"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="WAITING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("DESK", "Desk"),
                            ("QR", "QR Code"),
                        ],
                        default="ONLINE",
                        max_length=10,
                        verbose_name="source",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(default=0, verbose_name="priority"),
                ),
                (
                    "estimated_wait_time",
                    models.PositiveIntegerField(
                        default=15, verbose_name="estimated wait time"
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="joined at"),
                ),
                (
                    "called_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="called at"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="started at"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="clinics.clinic",
                        verbose_name="clinic",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tokens",
                        to="clinics.doctor",
                        verbose_name="doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="accounts.patientprofile",
                        verbose_name="patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Queue Token",
                "verbose_name_plural": "Queue Tokens",
                "db_table": "queue_token",
                "ordering": ["token_number"],
                "unique_together": {("clinic", "token_number", "token_label")},
            },
        ),
        migrations.CreateModel(
            name="QueueSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "current_token_number",
                    models.PositiveIntegerField(
                        default=0, verbose_name="current token number"
                    ),
                ),
                (
                    "total_patients",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total patients"
                    ),
                ),
                (
                    "completed_patients",
                    models.PositiveIntegerField(
                        default=0, verbose_name="completed patients"
                    ),
                ),
                (
                    "skipped_patients",
                    models.PositiveIntegerField(
                        default=0, verbose_name="skipped patients"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="started at"),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ended at"
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_sessions",
                        to="clinics.clinic",
                        verbose_name="clinic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Queue Session",
                "verbose_name_plural": "Queue Sessions",
                "db_table": "queue_session",
                "ordering": ["-date"],
                "unique_together": {("clinic", "date")},
            },
        ),
    ]
